CREATE TABLE post
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id     BIGINT                                  NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    category      INTEGER                                 NOT NULL,
    description   VARCHAR(255),
    localization  VARCHAR(255)                            NOT NULL,
    email_address VARCHAR(255),
    phone_number  VARCHAR(255),
    CONSTRAINT pk_post PRIMARY KEY (id)
);