CREATE TABLE category
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    icon_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

ALTER TABLE post
DROP
COLUMN category;

ALTER TABLE post
    ADD category BIGINT NOT NULL;

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_CATEGORY FOREIGN KEY (category) REFERENCES category (id);