CREATE TABLE image
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url   VARCHAR(255)                            NOT NULL,
    image BIGINT,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE post
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id     BIGINT                                  NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    category      INTEGER                                 NOT NULL,
    description   VARCHAR(255),
    localization  VARCHAR(255)                            NOT NULL,
    email_address VARCHAR(255),
    phone_number  VARCHAR(255),
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE post_image
(
    post_entity_id BIGINT NOT NULL,
    image_id       BIGINT NOT NULL,
    CONSTRAINT pk_post_image PRIMARY KEY (post_entity_id, image_id)
);

ALTER TABLE post_image
    ADD CONSTRAINT uc_post_image_image UNIQUE (image_id);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_IMAGE FOREIGN KEY (image) REFERENCES post (id);

ALTER TABLE post_image
    ADD CONSTRAINT fk_posima_on_image FOREIGN KEY (image_id) REFERENCES image (id);

ALTER TABLE post_image
    ADD CONSTRAINT fk_posima_on_post_entity FOREIGN KEY (post_entity_id) REFERENCES post (id);