/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gametrader.api;

import com.gametrader.api.model.InlineObject;
import com.gametrader.api.model.InlineObject1;
import com.gametrader.api.model.PostDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PostControllerApi
 */
@Ignore
public class PostControllerApiTest {

    private final PostControllerApi api = new PostControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPostTest() {
        InlineObject1 inlineObject1 = null;
        api.createPost(inlineObject1);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPostsTest() {
        List<PostDto> response = api.getAllPosts();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPostsByAuthorIdTest() {
        Long authorId = null;
        List<PostDto> response = api.getAllPostsByAuthorId(authorId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPostsByCategoryTest() {
        String category = null;
        List<PostDto> response = api.getAllPostsByCategory(category);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPostsByLocalizationTest() {
        String localization = null;
        List<PostDto> response = api.getAllPostsByLocalization(localization);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPostByIdTest() {
        Long id = null;
        PostDto response = api.getPostById(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePostTest() {
        InlineObject inlineObject = null;
        api.updatePost(inlineObject);

        // TODO: test validations
    }
    
}
